name: RELEASE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: PyPi
        env:
          PIP_PASSWORD: ${{ secrets.PIP_PASSWORD }}
        run: |
          bin/release/pypi.sh
      - name: DockerHub
        env:
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          bin/release/dockerhub.sh
